
library(shiny)
shinyUI(fluidPage(
  titlePanel("Comparing Models for Prediction of Horsepower from MPG"),
  h5("This app extends the methods presented in the Coursera class 
'Developing Data Products' for fitting a set of data to produce a 
prediction.

Linear and hockeystick models were developed in the course to 
predict horsepower from an automobile's average MPG (miles per gallon).
In addition to predictions generated by these two models, this app 
provides predictions generated by an exponential model.
Additionally, bootstrapped confidence 
intervals are calculated for the predictions from all three models 
in order to provide a measure of the error of the predictions."),
     
  h5("To use the app, move the slider to the desired MPG, select the
     models to be shown in the plot using the checkboxes and click 
     the 'Submit' button.  After a few seconds (during which confidence
     intervals are calculated by bootstrapping), the output will update 
     to reflect model predictions for horsepower, given the input MPG value."),
  h5("For each model, a prediction and a 95% confidence interval 
(generated by bootstrapping) are calculated.
For bootstrapped confidence intervals, the leftmost value is the 
0.025 quantile (the lower end of the 95% confidence interval) and the 
value to the right of this is the 0.975 quantile (the upper end of the 
95% confidence interval).  The 'scaled range' value in parentheses is 
the difference between these two quantile values scaled by the 
prediction value.  The scaled confidence interval range values are 
comparable across the three models and can be used to assess the 
model performance, with the smallest scaled range providing the best 
     performance."),
  sidebarLayout(
    sidebarPanel(
      sliderInput("sliderMPG", "What is the MPG of the car?", 10, 35, value = 20),
      checkboxInput("showModel1", "Show/Hide Linear (Lin) Model", value = TRUE),
      checkboxInput("showModel2", "Show/Hide Hockeystick (Hoc) Model", value = TRUE),
      checkboxInput("showModel3", "Show/Hide Exponential (Exp) Model", value = TRUE),
      submitButton("Submit"),
      plotOutput("plot1")
    ),
    mainPanel(
      h5("Linear model prediction:"),
      textOutput("pred1"),
      h5("95% Confidence Interval for linear model prediction (Scaled range):"),
      textOutput("boot1"),
      h5("Hockeystick model prediction:"),
      textOutput("pred2"),
      h5("95% Confidence Interval for hockeystick model prediction (Scaled range):"),
      textOutput("boot2"),
      h5("Exponential model prediction:"),
      textOutput("pred3"),
      h5("95% Confidence Interval for exponential model prediction (Scaled range):"),
      textOutput("boot3")
    )
  )
))